quarkus.application.name=inventory-service
quarkus.http.port=4545

# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=pg-inventory
quarkus.datasource.password=0706
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5444/pg-inventory

# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=no-file

# Flyway
quarkus.flyway.migrate-at-start=true

# Kafka
kafka.bootstrap.servers=localhost:9092

mp.messaging.incoming.orders-in.connector=smallrye-kafka
mp.messaging.incoming.orders-in.topic=orders.v1.events
mp.messaging.incoming.orders-in.group.id=inventory
mp.messaging.incoming.orders-in.auto.offset.reset=earliest
mp.messaging.incoming.orders-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.orders-in.failure-strategy=dead-letter-queue
mp.messaging.incoming.orders-in.dead-letter-queue.topic=orders.v1.events.dlq

mp.messaging.outgoing.orders-out.connector=smallrye-kafka
mp.messaging.outgoing.orders-out.topic=orders.v1.events
mp.messaging.outgoing.orders-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.low-stock-out.connector=smallrye-kafka
mp.messaging.outgoing.low-stock-out.topic=inventory.low-stock
mp.messaging.outgoing.low-stock-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.low-stock-dlq-out.connector=smallrye-kafka
mp.messaging.outgoing.low-stock-dlq-out.topic=inventory.low-stock.dlq
mp.messaging.outgoing.low-stock-dlq-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

auto.create.topics.enable=true